### ISSUE TITLE
Project 1 Study

### ISSUE THREAD

**Issue by jwoo0122** [kangjeongalliance/PintOS#5]
# 7월 1주차 진행상황
- 1-1, 1-2 완료 (sleep, priority 일부)
- 도큐먼트 읽고 크로스 체킹 진행 중

**Comment by jwoo0122** [comment]
## 브랜치 네이밍 컨벤션 및 협업 방식
- 각 프로젝트별로 project# 브랜치 생성
- 플젝 별 소단위 마일스톤에 대해 #-#/username 으로 브랜치 생성, 각자 브랜치에서 작업
- 작업 내용에 대해 공유, 완성된 코드를 project# 에 머지 후 다음 작업 진행
- master 는 플젝 하나 끝날때마다 PR 날리면 좋을 듯.

**Comment by apple12347678** [comment]
> ## 브랜치 네이밍 컨벤션 및 협업 방식
> * 각 프로젝트별로 project# 브랜치 생성
> * 플젝 별 소단위 마일스톤에 대해 #-#/username 으로 브랜치 생성, 각자 브랜치에서 작업
> * 작업 내용에 대해 공유, 완성된 코드를 project# 에 머지 후 다음 작업 진행
> * master 는 플젝 하나 끝날때마다 PR 날리면 좋을 듯. @apple12347678

Good!
